#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

require() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing dependency: $1"; exit 1; }
}

require docker
require npx

echo "[dev-local] Starting Redis + SRH..."
docker compose -f scripts/docker-compose.local.yml up -d

if [[ ! -f supabase/config.toml ]]; then
  echo "[dev-local] Initializing Supabase project..."
  npx --yes supabase init --force --with-vscode-settings=false
fi

echo "[dev-local] Starting Supabase..."
if ! npx --yes supabase status >/dev/null 2>&1; then
  npx --yes supabase start
else
  echo "[dev-local] Supabase already running."
fi

# Parse `supabase status -o env` for the values we need.
status_env="$(npx --yes supabase status -o env)"
api_url="$(echo "$status_env" | awk -F= '/^API_URL=/{print $2}' | tr -d '"')"
service_role_key="$(echo "$status_env" | awk -F= '/^SERVICE_ROLE_KEY=/{print $2}' | tr -d '"')"

if [[ -z "$api_url" || -z "$service_role_key" ]]; then
  echo "[dev-local] Failed to read Supabase status. Run 'npx supabase status' to debug."
  exit 1
fi

# Persist HMAC secret across restarts.
secret_file=".dev-local-secret"
if [[ ! -f "$secret_file" ]]; then
  node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" > "$secret_file"
fi
waitlist_secret="$(cat "$secret_file")"

mkdir -p tmp/emails

cat > .env.local <<EOF
# Auto-generated by scripts/dev-local.sh — do not commit.
PUBLIC_SITE_URL=http://localhost:4321

SUPABASE_URL=$api_url
SUPABASE_SERVICE_ROLE_KEY=$service_role_key

# Empty → resend.ts writes HTML to tmp/emails/ instead of sending.
RESEND_API_KEY=
RESEND_FROM_EMAIL=Syncologic <hi@syncologic.local>

WAITLIST_TOKEN_SECRET=$waitlist_secret

KV_REST_API_URL=http://127.0.0.1:8079
KV_REST_API_TOKEN=local-dev-token
KV_REST_API_READ_ONLY_TOKEN=local-dev-token
EOF

echo "[dev-local] Wrote .env.local."
echo "[dev-local] Supabase Studio: http://127.0.0.1:54323"
echo "[dev-local] Emails: tmp/emails/"
echo "[dev-local] Starting astro dev..."
exec npx astro dev
